#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__

#define USE_WIFI_MODE		STATION_MODE
#define WIFI_CLIENTSSID		"router ssid"
#define WIFI_CLIENTPASSWORD	"router password"
#define TCPSERVERPORT		1000

//IP E PORTA UDP PARA ENVIO E RECEBIMENTO
#define UDP_BROADCAST_IP    "192.168.0.239"
#define UDP_DEFAULT_PORT    1000

//USUARIO E SENHA DO ROTEADOR
#define WIFI_SSID           "ZION"
#define WIFI_PASS           "P4$$w0rd"

//DESCOMENTE ESSA LINHA PARA USAR O DEBUG
#define DEBUG_SERIAL

#endif
