ESP8266

this project is integrated with netbeans IDE

obs: this works for windows now but you can use the linux to

open the Makefile edit the this line to your location:
ROOT=C:/GitHub/ESP8266/netbeans_project/project

and this line to for the toolchain folder:
TOOLCHAIN=C:/ToolChains/GNU_XTENSA/bin/xtensa-lx106-elf

my tolchain name: xtensa-lx106-elf

for windows you need to -> MINGW GCC

the binary files are generated on: /build
